# Generated by Django 5.1.7 on 2025-03-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plainte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainte',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plainte',
            name='status',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='en attente', max_length=20),
        ),
    ]
